# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build ...aX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "ovos_phal_plugin_aiy_v2/version.py"
      - "test/**"
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "CHANGELOG.md"
      - "MANIFEST.in"
      - "readme.md"
      - "scripts/**"
  workflow_dispatch:

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@master
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
    with:
      version_file: "ovos_phal_plugin_aiy_v2/version.py"
      publish_prerelease: true
      update_changelog: true
      alpha_var: VERSION_ALPHA
      build_var: VERSION_BUILD
      minor_var: VERSION_MINOR
      major_var: VERSION_MAJOR
